# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coordinates',
            new_name='long',
        ),
        migrations.AddField(
            model_name='location',
            name='lag',
            field=models.FloatField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
